version: 2.1

executors:
  ci-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    working_directory: ~/mihail-yartsev/MihailYartsev.HttpClientGenerator

jobs:
  build:
    executor: ci-executor
    steps:
      - checkout
      - run: dotnet restore
      - run: cd tests/MihailYartsev.HttpClientGenerator.Tests
      - run: dotnet test --test-adapter-path:. --logger:"xunit;LogFilePath=./../../testresults/out.xml"
      - run: cd ../..
      - run: dotnet pack src/MihailYartsev.HttpClientGenerator/MihailYartsev.HttpClientGenerator.csproj -c release -o ./../../package
      - persist_to_workspace:
          root: ~/mihail-yartsev/MihailYartsev.HttpClientGenerator
          paths:
            - package
      - store_test_results:
          path: ./testresults
  deploy:
    executor: ci-executor
    steps:
      - attach_workspace:
          at: ~/mihail-yartsev/MihailYartsev.HttpClientGenerator
      - run: dotnet nuget push package/*.nupkg -k $Nuget_Api_Key -s https://api.nuget.org/v3/index.json

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master